# Generated by Django 4.2.1 on 2023-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('model', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='products')),
                ('category', models.CharField(max_length=120)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='products.tag')),
            ],
        ),
    ]
