# Generated by Django 4.2.3 on 2023-07-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
